0.21 review
Gregicality/gregicality pull request #237
Opened 2020-11-09 16:36 UTC by huneau

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactor.java
> +            this.boosted = drainOxygenStack != null && drainOxygenStack.amount >= 2 && drainCryotheumStack != null && drainCryotheumStack.amount >= 250;
@hjae78 consistency 
![image](https://user-images.githubusercontent.com/9199240/99179556-416c0600-271f-11eb-8b95-d3eb38902d89.png)

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactor.java
> +            FluidStack drainOxygenStack = fluidTank.get().drain(oxygenStack, false);
maybe plasma oxygen ? oxygen is really easy to get.
there tier above using plasma potassium with naqadah fuel
and liquid cryothuem is not really a challenge

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactorUEV.java
> +            this.boosted = drainOxygenStack != null && drainOxygenStack.amount >= 2 && drainCryotheumStack != null && drainCryotheumStack.amount >= 250;
@hjae78 same as above consistency 
![image](https://user-images.githubusercontent.com/9199240/99179607-9f005280-271f-11eb-8f3a-9cbb32d56c30.png)

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactorUEV.java
> +            FluidStack drainOxygenStack = fluidTank.get().drain(oxygenStack, false);
same here, just oxygen and supercooledcryothuem, I dont see challenge here

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactorUHV.java
> +            this.boosted = drainOxygenStack != null && drainOxygenStack.amount >= 2 && drainCryotheumStack != null && drainCryotheumStack.amount >= 250;
@hjae78 same
![image](https://user-images.githubusercontent.com/9199240/99179629-ca833d00-271f-11eb-883c-5e63bff05062.png)

2020-11-15 07:52 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/advance/hyper/HyperReactorUHV.java
> +            FluidStack oxygenStack = Materials.Oxygen.getPlasma(4);
oxygen and supercooledcryothuem again ?

2020-12-07 13:00 UTC, huneau commented on src/main/java/gregicadditions/recipes/GARecipeAddition.java
> +        FUSION_RECIPES.recipeBuilder().fluidInputs(Lead.getFluid(125), Zinc.getFluid(125)).fluidOutputs(Copernicium.getFluid(16)).duration(128).EUt(49152).EUToStart(480000000).buildAndRegister();
@hjae78 I want polonium to get copernicium, because copericium is used for something after nuclear step

2020-12-07 17:39 UTC, hjae78 requested changes

2020-12-07 17:39 UTC, hjae78 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final DustMaterial SodiumSulfate = new DustMaterial(890, "sodium_sulfate", 0xFFFFFF, MaterialIconSet.ROUGH, 2, of(), 0);
Should change to simple dust material

2020-12-07 17:39 UTC, hjae78 commented on src/main/resources/assets/gtadditions/lang/en_us.lang
> +gtadditions.machine.fusion_.nameting_3.name=Fusion Casing MK3
This looks strange

2020-12-07 20:16 UTC, huneau commented on src/main/resources/assets/gtadditions/lang/en_us.lang
> +gtadditions.machine.fusion_.nameting_3.name=Fusion Casing MK3
maybe my cat trolling me

2020-12-07 20:17 UTC, huneau commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final DustMaterial SodiumSulfate = new DustMaterial(890, "sodium_sulfate", 0xFFFFFF, MaterialIconSet.ROUGH, 2, of(), 0);
yes but for now, dont touch anything

2021-01-02 13:51 UTC, merged