Stop non-fusion related multiblocks from using superconducting and fusion coils
Gregicality/gregicality pull request #330
Opened 2021-01-22 02:42 UTC by TechLord22

This prevents the superconducting and fusion coils from working in the EBF, Volcanus, Chemical Plant, Pyrolyse Oven, and Cracker Unit. They are also removed from the machines' JEI previews. There is only one potential recipe issue - which is Abyssal Alloy. This material uses 9625K in the EBF. This change would prevent it from being created until the Advanced Heating Coil Mk1. This coil requires Trinium, which requires the Mk2 Void Miner, which requires many materials using UHV voltage. Nearly every UHV singleblock, transformer, and energy hatch uses Abyssal Alloy cables or wires - making progressing to UHV impossible. The solution to this is to change the coil to not utilize Trinium in its recipe. Though, I believe this may have already been addressed and fixed elsewhere. 

Additionally, I do not think it is possible to remove the EBF and Multismelter info tooltips from the Superconducting and Fusion Coils, so hiding/removing them and replacing them with Gregicality's own versions may be necessary.

2021-01-22 08:23 UTC, huneau commented
hum interresting 🤔

2021-01-22 09:11 UTC, hjae78 commented
I had this exact idea but never got around to it! Please add a config option for this please

2021-01-22 09:29 UTC, YoungGT commented
Config needed.

2021-01-22 10:02 UTC, hjae78 commented
As regards to Abyssal Alloy I'd rather just see its temperature lowered

2021-01-23 00:21 UTC, hjae78 requested changes

2021-01-23 00:21 UTC, hjae78 commented on src/main/java/gregicadditions/GAConfig.java
> +            @Config.Name("GTCEHeatingCoilBlacklist")
Please include spaces in the name parameter

2021-01-23 16:11 UTC, hjae78 approved these changes

2021-01-23 16:16 UTC, merged

2021-01-23 16:17 UTC, hjae78 commented
Good job!