Cosmic Circuits
Gregicality/gregicality pull request #335
Opened 2021-01-26 15:25 UTC by pablocnvs

2021-01-26 16:43 UTC, hjae78 requested changes

2021-01-26 16:43 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/chain/CosmicComponents.java
> +        FUSION_RECIPES.recipeBuilder().fluidInputs(Americium.getFluid(144), Titanium.getFluid(144)).fluidOutputs(Tennessine.getFluid(288)).duration(100).EUt(75000).EUToStart(520000000).buildAndRegist
There should be Advanced Fusion recipes

2021-01-26 16:48 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/CosmicComponents.java
> +        FUSION_RECIPES.recipeBuilder().fluidInputs(Americium.getFluid(144), Titanium.getFluid(144)).fluidOutputs(Tennessine.getFluid(288)).duration(100).EUt(75000).EUToStart(520000000).buildAndRegist
I thought it was going to be too much, but then i remembered that people use AE or RS to automate it, so it will probs be tier 2 advanced fusion

2021-01-27 19:01 UTC, a-thoren approved these changes

2021-01-27 19:03 UTC, merged

2021-01-27 19:03 UTC, hjae78 commented
Good job!