Steam Grinder Multiblock
Gregicality/gregicality pull request #339
Opened 2021-01-29 09:50 UTC by DStrand1

The Steam Grinder:
![SteamGrinderOverview](https://user-images.githubusercontent.com/10861407/106257678-7c3fef00-61e2-11eb-8e35-4d3a0f2220c4.png)

The Steam Grinder (adapted from GT++) is a Steam-Era multiblock to serve as an alternative to the terribly slow Steam, LV, and even MV Macerators. It's only downside past that is that it is not very efficient at doing single crafts (similar to the Multismelter), and has no secondary outputs. It can process up to 8 of an item at once, using formulas:

`duration = Math.max(recipeDuration, recipeDuration * 1.5)`
`totalEUt  = Math.min(32, Math.ceil(recipeEUt * 1.33))`

This simplifies roughly to `duration * 1.5` and `recipeEUt * 1.33`, but handles some edge cases.

Note that this multiblock uses new Steam I/O busses, and a new Steam Hatch, which is basically an Energy Input Hatch, but for Steam. It will NOT form with normal I/O busses, and does not accept normal Fluid I/O hatches either.
![DoesntForm](https://user-images.githubusercontent.com/10861407/106258878-16546700-61e4-11eb-8fc9-1086ab60ef2e.png)

Here are the recipes:
![GrinderRecipe](https://user-images.githubusercontent.com/10861407/106258934-29ffcd80-61e4-11eb-859c-704030f87b2d.PNG)
![SteamHatchRecipe](https://user-images.githubusercontent.com/10861407/106258938-2b30fa80-61e4-11eb-8472-eb31125a2b59.png)
![SteamInputBusRecipe](https://user-images.githubusercontent.com/10861407/106258941-2c622780-61e4-11eb-8217-fe8cd08a1f5b.png)
![SteamOutputBusRecipe](https://user-images.githubusercontent.com/10861407/106258943-2d935480-61e4-11eb-93a0-783021ac19bc.png)

And the tooltip for the Steam Grinder block:
![ControllerTooltip](https://user-images.githubusercontent.com/10861407/106258998-3edc6100-61e4-11eb-8d7a-25d293d70a4b.png)

Note that the secondary metal used here is Tumbaga, matching how it was done in GT++. Because I wanted to preserve this, I changed Tumbaga to be a smeltable dust instead of an EBF dust. It still requires some Gold to make, but this way, it gives players a reason to push for Gold early, and try to get to the better path of acquiring it. All in all, this multiblock does not require too much Tumbaga, so it is still achievable in Steam/LV.

Additionally, I added the GT++ Style shapeless recipes for Tumbaga, by adding a new dust, Tumbaga Mix. If this change seems unnecessary, and we want to keep this machine gated by a Mixer, I can revert it.

Lastly, the JEI preview:
![MultiblockPattern](https://user-images.githubusercontent.com/10861407/106259291-a7c3d900-61e4-11eb-9be2-7e0f79afe564.PNG)

In order to create this, I had to create many parent classes capable of handling a multiblock that uses Steam. This means that we can relatively easily add new Steam Multiblocks if we wish to in the future. Note that the parent class 'RecipeMapSteamMultiblockController` is coded specifically to NOT allow fluid I/O other than the Steam Hatch, which is not included in recipe matching, so this will limit the abilities of Steam multiblocks.

Thank you for considering this addition to Gregicality, as it took a lot of work to build these parent classes, and to create the recipe logic allowing for multiple items of a single recipe to process at once.

2021-01-29 11:37 UTC, hjae78 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static DustMaterial TumbagaMix = new DustMaterial(775, "tumbaga_mix", 0xFFB20F, MaterialIconSet.DULL, 2, of(new MaterialStack(Gold, 2), new MaterialStack(Bronze, 1)), 0);
I don't understand why this is added? You say that it's to introduce a shapeless recipe (?) for Tumbaga but then why not just add a recipe using the exisiting Tumbaga material?

2021-01-29 11:37 UTC, hjae78 commented on src/main/java/gregicadditions/machines/GATileEntities.java
> +        STEAM_HATCH = GregTechAPI.registerMetaTileEntity(4200, new MetaTileEntitySteamHatch(location("steam_hatch")));
This won't cause any ID shifts as it simply registers the tile entity at the number you specify, you absolutely don't need to skip forward in the ID here and I'd prefer if we continued where we previously left at 4174.

2021-01-29 11:37 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/impl/GAMultiblockAbility.java
> +    public static final MultiblockAbility<IItemHandlerModifiable> STEAM_IMPORT_ITEMS = new MultiblockAbility<>();
Are you sure this needs to be in a new class the extends MultiblockAbility? We have new MultiblockAbility declared in GregicAdditionsCapabilities, where the Qubit hatches are registered.

2021-01-29 11:37 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/impl/RecipeMapSteamMultiblockController.java
> +}
How come you can't extend RecipeMapMultiblockController? As far as I can see all you're doing differently is changing recipemapWorkable

2021-01-29 11:37 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/GARecipeAddition.java
> +        ModHandler.addShapelessRecipe("tumbaga_mix_shapeless", OreDictUnifier.get(dust, TumbagaMix),
Ah now I see why you added Tumbaga Mix. It should be SimpleDustMaterial though. Also these recipes can have ItemStacks with size larger than 1 I'm quite sure

2021-01-29 11:40 UTC, DStrand1 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static DustMaterial TumbagaMix = new DustMaterial(775, "tumbaga_mix", 0xFFB20F, MaterialIconSet.DULL, 2, of(new MaterialStack(Gold, 2), new MaterialStack(Bronze, 1)), 0);
Tumbaga is 7 Gold dust and 3 Bronze dust in a mixer, so there wasn't any way I could make it handcraftable otherwise

2021-01-29 11:41 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/GATileEntities.java
> +        STEAM_HATCH = GregTechAPI.registerMetaTileEntity(4200, new MetaTileEntitySteamHatch(location("steam_hatch")));
Alright, I will adjust it. I left some space cause when I was working on this, the Cosmic Ray TE hadn't been added yet, as it was in a very recent commit

2021-01-29 11:41 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/impl/GAMultiblockAbility.java
> +    public static final MultiblockAbility<IItemHandlerModifiable> STEAM_IMPORT_ITEMS = new MultiblockAbility<>();
Ok, I will refactor to this. I didn't see that we had a place for it already.

2021-01-29 11:43 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/impl/RecipeMapSteamMultiblockController.java
> +}
I wanted to remove the notion of Fluid inputs to make Steam easier to implement. In hindsight, what you are suggesting may have been possible though. If you'd like me to restructure to that, I can

2021-01-29 11:44 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/GARecipeAddition.java
> +        ModHandler.addShapelessRecipe("tumbaga_mix_shapeless", OreDictUnifier.get(dust, TumbagaMix),
I tried that, and it showed itemstacks with amounts of greater than one in the shapeless recipe, instead of breaking them up. Then when crafting, it only took one of that material. Kind of a weird system, but whatever

2021-01-29 13:23 UTC, huneau commented
I not sure to want that, but The only thing I can say its thanks  lot for your job and its seams really well done. I will make you a review later

2021-01-29 17:55 UTC, hjae78 commented
Even if decal declines this I think you've done a great job and this opens up a lot of options for the future and you should definitely release this as a standalone addon!

2021-01-29 18:46 UTC, huneau requested changes

2021-01-29 18:46 UTC, huneau commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static DustMaterial TumbagaMix = new DustMaterial(775, "tumbaga_mix", 0xFFB20F, MaterialIconSet.DULL, 2, of(new MaterialStack(Gold, 2), new MaterialStack(Bronze, 1)), 0);
it should be removed

2021-01-29 18:46 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/impl/RecipeMapSteamMultiblockController.java
> +package gregicadditions.machines.multi.impl;
it should be placed in gregicadditions.capabilities.impl

2021-01-29 18:46 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/impl/SteamMultiblockRecipeLogic.java
> +package gregicadditions.machines.multi.impl;
it should be placed in gregicadditions.capabilities.impl

2021-01-29 18:46 UTC, huneau commented on src/main/java/gregicadditions/machines/multi/steam/MetaTileEntitySteamGrinder.java
> +        protected Recipe findRecipe(long maxVoltage, IItemHandlerModifiable inputs, IMultipleTankHandler fluidInputs) {
I trust you on algo

2021-01-29 18:46 UTC, huneau commented on src/main/java/gregicadditions/recipes/GARecipeAddition.java
> +        ModHandler.addShapelessRecipe("tumbaga_mix_shapeless", OreDictUnifier.get(dust, TumbagaMix),
should be removed, because tumbaga is for advanced stuff

2021-01-29 18:46 UTC, huneau commented
if @DStrand1 fix all comment @hjae78 you can merge

2021-01-29 21:03 UTC, DStrand1 commented
With regards to extending `RecipeMapMultiblockController` instead of `MultiblockWithDisplayBase` for my parent class, I have to do this for 3 reasons.
1. To remove the notion of fluid inputs other than Steam
2. To allow for a different front Overlay texture
3. To properly use my new RecipeLogic class, as otherwise I would not be able to use `SteamMultiblockRecipeLogic`, since I had to have it extend `AbstractRecipeLogic` and not `MultiblockRecipeLogic`.

All other requested changes have been resolved and committed.

2021-01-30 09:48 UTC, hjae78 commented
Okay it looks good now, but I can see an issue with the recipe since as decal said Tumbaga is for higher tier stuff. The EBF temperature should be restored. Instead we could use Potin, this does not have an EBF temperature and is alloyed from early game materials

2021-01-31 01:36 UTC, DStrand1 commented
Alright, Tumbaga is back to where it is on master. I changed all my Steam Grinder components that used Tumbaga to use Potin instead, similar to the Large Macerator. As a bonus, it is not gated by anything, so it solves my problems and yours too. This should be ready to merge now.

2021-01-31 08:14 UTC, hjae78 commented
Great! Thanks for your hard work!

2021-01-31 08:14 UTC, merged