Steam Oven
Gregicality/gregicality pull request #356
Opened 2021-02-06 08:00 UTC by DStrand1

**What:**
This PR expands on the newly added Steam Multiblock parent classes, and adds a new multiblock inspired by the Railcraft Steam Oven, the brother to the Steam Grinder in 1.7.10 GT packs.

**How solved:**
The Steam Oven:
![Overview](https://user-images.githubusercontent.com/10861407/107112607-7c616f80-681e-11eb-9ae1-0969828e60c3.png)

It follows convention with the boilers, and lights up the Firebox Casings when active:
![active](https://user-images.githubusercontent.com/10861407/107112616-93a05d00-681e-11eb-8b25-72df5278a111.png)

I chose to use Firebox Casings for this since I wanted to make it a bit cheaper than the Steam Grinder, as Railcraft's was a 2x2x2 multiblock.

The recipe, which is also a little cheaper than the Steam Grinder, but not much (uses Invar for gears, like the MultiSmelter):
![recipe](https://user-images.githubusercontent.com/10861407/107112637-bc285700-681e-11eb-82d9-dd07dcfde0fb.PNG)

And lastly, the tooltip and JEI preview:
![tooltip](https://user-images.githubusercontent.com/10861407/107112628-adda3b00-681e-11eb-823c-32085ec8bab5.png)
![JEIPreview](https://user-images.githubusercontent.com/10861407/107112659-d7936200-681e-11eb-846e-bcfbf116e1c1.PNG)

**Outcome:**
Added Steam Oven

**Additional info:**
- I separated the nested `SteamGrinderWorkable` class and added a parameter for the number of items to process. I left it at 8 for this multiblock as well, but this makes it more flexible for the future. 
- I also added a new config entry for the `Steam -> EU` conversion rate for Steam Multiblocks. The standard rate used by single block Steam machines is 1:1, but for these, I decided to set their default to 2 Steam -> 1EU to balance it. It is still saving Steam overall compared to single block machines though.

2021-02-06 10:07 UTC, huneau commented
should fix the multiblock and even the grinding with the correct ga metal casing

2021-02-06 10:07 UTC, huneau commented
otherwise its a good job :)

2021-02-06 19:40 UTC, hjae78 requested changes

2021-02-06 19:40 UTC, hjae78 commented on src/main/java/gregicadditions/jei/multi/simple/SteamOvenInfo.java
> +                .where('X', MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.BRONZE_BRICKS))
As decal said, change this line to use the Gregicality Bronze casing as we use that as a standard

2021-02-07 01:18 UTC, DStrand1 commented on src/main/java/gregicadditions/jei/multi/simple/SteamOvenInfo.java
> +                .where('X', MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.BRONZE_BRICKS))
I tried changing it to `GAMetaBlocks.getMetalCasingBlockState(Materials.Bronze)` and it threw a NPE. Am I doing this wrong?

2021-02-09 06:10 UTC, aimiebell commented on src/main/java/gregicadditions/GAConfig.java
> +        @Config.Comment({"Steam to EU multiplier for steam multiblocks. 1.0 means 1 Steam -> 1EU. 2.0 means 1 Steam -> 2EU. 0.5 means 2 Steam -> 1EU"})
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-02-09 08:56 UTC, hjae78 commented on src/main/java/gregicadditions/GAConfig.java
> +        @Config.Comment({"Steam to EU multiplier for steam multiblocks. 1.0 means 1 Steam -> 1EU. 2.0 means 1 Steam -> 2EU. 0.5 means 2 Steam -> 1EU"})
What, that's a class not a method

2021-02-10 15:35 UTC, hjae78 commented
Are we currently stuck on the firebox casings being mismatched with the generated bronze casing?

2021-02-10 23:49 UTC, DStrand1 commented
Yes, this PR is still held up by issues with the casings:

- Generated casings would have the wrong recipe, using Frames instead of Bricks
- Generated casings would have a different color from Firebox Casings
- There is problems with generating a new Firebox, not sure if it is possible
- These same problems would now be present in the Large Bronze Boiler

2021-02-11 11:15 UTC, hjae78 commented
@huneau it is ok for me to proceed with the casing as is. We can imagine these Bronze casings as a special type of casing like we have for other machines.

2021-02-11 11:21 UTC, huneau commented
merge it, I will fix it

2021-02-11 11:42 UTC, merged