Fix Some Outstanding Issues
Gregicality/gregicality pull request #373
Opened 2021-02-22 03:59 UTC by DStrand1

- Fixes #315:
See https://github.com/Shadows-of-Fire/Shadows-of-Greg/pull/106 for a description of the fix for this issue.

- Fixes #168:
This issue occurred for any Mixer recipe that had an integrated circuit, but there only happen to be two so far. I added a section of code in the Large Mixer recipe builder to iterate over all inputs, and if it finds a circuit, it removes it from the input list. I also had to save that circuit value, and use it instead of the default logic of `total input items/fluids count` to avoid a conflict.

- Fixes #366:
I added a circuit of configuration 1 to the standard Aluminium EBF recipe. The EUt, duration, and blastTemp are all identical.

- Fixes #271:
I added the flag `EXCLUDE_BLOCK_CRAFTING_RECIPES` and added each recipe manually to use 4 instead of 9.

Each issue I fixed has a different commit, so if you want to see the individual changes for each issue, you can view that commit's changes.

2021-02-22 08:55 UTC, hjae78 requested changes

2021-02-22 08:55 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/RecipeHandler.java
> +            if (circuitIngredient == null)
I think this can open potential conflicts in the future. Imagine a recipe that takes a circuit in normal mixer and there exists a subset of the inputs of size equal to the circuit number that has a separate mixer recipe. Then if we run this recipe in Large Mixer we have a conflict. To solve this you should just filter out the circuit and not save it on row 473.

2021-02-22 08:56 UTC, hjae78 commented
Thanks for the help, really appreciate it!

2021-02-22 12:06 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/RecipeHandler.java
> +            if (circuitIngredient == null)
I added this because if I hadn't, the two recipes I fixed in this change would conflict since they have the same exact inputs, but different amounts. What I did may not be the best solution, but simply using the existing way of setting a circuit value does not work either.

2021-02-23 20:01 UTC, hjae78 requested changes

2021-02-23 20:05 UTC, merged