Yet Another PA Change
Gregicality/gregicality pull request #385
Opened 2021-02-28 05:07 UTC by DStrand1

First off, this PR includes the commits of #380, so if it or this PR is merged, it will be included in the code base.

This PR optimizes the PA heavily by creating a set of parent classes to allow for a slot in the multiblock controller.
![image](https://user-images.githubusercontent.com/10861407/109408408-195f8600-794f-11eb-8c77-86cf420e5d7e.png)

This slot is dynamic, as I have it as part of a parent class, `RMapMultiblockWithSlotController`. As per my current implementation, you pass in a class, the slot can hold an item that extends that class. For the PA, I chose `ITieredMetaTileEntity`. With these parent classes, we could optionally use this for circuits in recipes in our Large multiblocks. 

Now, for the reasoning. Consider this example:
- I have a PA with 3 MAX input buses on it
- I have all the slots full of items, none of which are a valid machine to use for recipes

Now our PA will be lagging an amazing amount as it loops through all slots in all input buses, looking for a machine that doesn't exist. And to make this even better, it is comparing against a List of MTE's. With this change, it will never check the input buses unless a valid machine is in the controller slot, thus optimizing the PA by a drastic margin.

Additionally, I added some text to its GUI to show the RecipeMap and Parallel Recipes the PA is able to handle given its machine input. This max value also responds to the Config limit.
![Capture](https://user-images.githubusercontent.com/10861407/109408558-77409d80-7950-11eb-9ea2-7195443a7474.PNG)

2021-03-01 01:47 UTC, DStrand1 commented
This git hierarchy looks very strange, but it is ready to merge now, and all works as intended.

2021-03-01 09:45 UTC, huneau requested changes
As always, nice job

2021-03-01 09:45 UTC, huneau commented on src/main/java/gregicadditions/capabilities/impl/RMapMultiblockWithSlotController.java
> +public abstract class RMapMultiblockWithSlotController extends GARecipeMapMultiblockController {
Write class in full word, this help when searching

2021-03-01 09:45 UTC, huneau commented on src/main/java/gregicadditions/gui/GAGuiTextures.java
> +public class GAGuiTextures {
you can you the client handler class

2021-03-01 11:00 UTC, DStrand1 commented
Requested changes have been addressed. I also fixed the compilation issue I described in https://discord.com/channels/701354865217110096/792756247689822239/815830216520892436 since it kept me from testing my changes here.

2021-03-01 11:07 UTC, huneau approved these changes

2021-03-02 11:11 UTC, hjae78 approved these changes

2021-03-02 14:38 UTC, merged