Update Chemistry for consistancy with GTCE
Gregicality/gregicality pull request #388
Opened 2021-03-01 23:33 UTC by TechLord22

This PR is planned to update every chemistry recipe added by Gregicality to use the GTCE chemistry changes. Most of the chains need to have the items with decomposition multiplied by the number of constituents. This was originally started with the intention to create combined recipes in the chemical plant for the late game, those will come in a separate PR after this one is complete.

List of Chains Covered (by file):
- [ ] Aluminium Chain
- [ ] Ammonia Chain
- [ ] Barium Chain
- [ ] Brine Chain
- [ ] Chromium Chain
- [ ] Cosmic Components
- [ ] Dyes
- [ ] Fullerene Chain
- [ ] Fusion Elements Chain
- [ ] Gold Chain
- [ ] Iodine Chain
- [ ] Lithium Chain
- [ ] Nanotube Chain
- [ ] Naquadah Chain
- [ ] Niobium Tantalum Chain
- [ ] Nuclear Chain
- [ ] PEEK Chain
- [ ] Plastic (PBI) Chain
- [ ] Platinum etc. Chain
- [ ] Rare Earth Element Chain
- [ ] Rhenium Chain
- [ ] Selenium Chain
- [ ] Sensor/Emitter Material Chains
- [ ] Superconductors SMD Chains
- [ ] Supra-Causal Components Chains
- [ ] Tungsten Chain
- [ ] UHV Materials Chains
- [ ] Ultimate Materials Chains
- [ ] Uranium Chain
- [ ] Vanadium Chain
- [ ] Various Chains
- [ ] Zinc Chain
- [ ] Zircon Chain
- [ ] Zylon Chain
- [ ] GARecipeAddition (potentially)

2021-03-02 01:01 UTC, DStrand1 commented
A list of (currently) changed files, with checkboxes for if I have reviewed the chemistry in them:
- [ ] GAMaterials
- [ ] GARecipeAddition
- [ ] AluminiumChain
- [ ] AmmoniaChain
- [ ] BariumChain
- [ ] BrineChain
- [ ] ChromiumChain
- [ ] CosmicComponents
- [ ] Dyes
- [ ] FullerineChain
- [ ] FusionElementsChain
- [ ] GoldChain
- [ ] IodineChain
- [ ] NanotubeChain
- [ ] NaquadahChain
- [ ] NiobiumTantalumChain
- [ ] NuclearChain
- [ ] PEEKChain
- [ ] PlasticChain
- [ ] PlatinumSludgeGroupChain
- [ ] REEChain
- [ ] RheniumChain
- [ ] SeleniumChain
- [ ] SensorEmitter
- [ ] SuperconductorsSMDChain
- [ ] ZylonChain
- [ ] GrowthMedium
- [ ] SterilizedGrowthMedium
- [ ] en_us

2021-03-02 07:51 UTC, DStrand1 commented
With this REEChain finalization, the step:
`REChlorides + Diethylhexyl Phosphoric Acid -> NaOH + REE's ...`
The Diethylhexyl Phosphoric Acid was not consumed in the process, so I changed it to consume 10mB instead of 1B, so that the player still needs to make it, but does not burn through it extremely quickly. This is my "fluid catalyst" solution for now.

2021-03-21 03:28 UTC, DStrand1 commented
In the last commit `d4a6189` I removed the FluidMaterial "Dimethylbenzene" because it is simply another name for Xylene. I needed Xylene to be lowered significantly in tier for my Kapton circuit board work, so I decided to lower Ortho-Xylene (the first in the chain) to MV-tier, where Dimethylbenzene was previously. This frees up another GT material ID.

2021-04-01 06:19 UTC, DStrand1 commented
The last commit cleans up a bunch of code in the recipes package. Mostly, it ensures that:
- Methods and parameters are properly Nonnull/Nullable
- Variables are set to final
- Deprecated methods are not being used
- Warnings are suppressed for things like CT methods

2021-04-04 07:01 UTC, DStrand1 commented
For those paying loose attention to this branch, with that last commit, that means that we are done with the second phase of this PR. Now, we have one last review of a few things, mostly cleaning up some remaining TODOs and some things in GAMaterials.

Nearly there!

2021-04-06 01:38 UTC, DStrand1 commented
Marking this PR as Ready To Review

2021-04-06 02:09 UTC, DStrand1 approved these changes

2021-04-06 02:11 UTC, Yefancy approved these changes

2021-04-06 16:55 UTC, Zalgo239 approved these changes

2021-04-07 06:36 UTC, hjae78 commented
Have you run your recipe conflict tests on this?

2021-04-07 10:33 UTC, Pnc6lx commented
i want to know if we can have those ore dust process in ebf back? it was add to improve duction from ores. after this change, many ore contain less elements than before. so i want more output, like more dust in one ore, or add them back

2021-04-07 12:15 UTC, TechLord22 commented
Balancing those EBF recipes would make them completely equivalent to electrolysis, except that they would take the extra step in the EBF. There wouldn't be a benefit to them anymore, which is why they were removed.

2021-04-07 12:26 UTC, Pnc6lx commented
so can we get more crushed ores from ore?

2021-04-07 13:08 UTC, pablocnvs commented
Are there any MV ores that require the EBF? Those could be considered

2021-04-07 15:26 UTC, Pnc6lx commented
maybe barite? although is hv, and i find diborane have a ebf recipe use 1 B dust and out 3 B dust. and after you delete these recipe, their is no recipe for CoO, whitch is used in 3recipe

2021-04-07 15:42 UTC, Pnc6lx commented
and Ba ingot in ebf is strange. it should be 4BaO + 2Al to 3Ba + BaAl2O4, so input 8 BaO dust and 2Al dust, output 3Ba ingot 7BaAlO4

2021-04-08 15:47 UTC, pablocnvs requested changes
Overall great job. Truly amazed by this. There are a handful of things i want to comment about, but it is really a tiny portion of this.
Also, are there any compounds that are unused? You could mark them in GAMaterials so we know for future updates as well as further revision

2021-04-08 15:47 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // C19H14 + O -> C18H12 + CH2O
Benzophenanthrenylacetonitrile is C20H13N
So C19H14 + KCN + Bromosuccinimide -> C20H13N + KBr + Succinimide
The only problem is that it is 3 item inputs and three item outputs, but it is chemically correct.

2021-04-08 15:47 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // 10C18H12 + 60O -> 3C60 + 60H2O
Technically most of the hydrogens leave in the folding step, so there doesn't need to be that many oxygens. Since it is going to need the large engraver and we have plans for that to have multiple fluid inputs and outputs, many of the hydrogens can be removed at that step.
So we need to turn C20H13N into C60H30, so i suggest this 
3 C20H13N + (SOCl2,KOH,TiAlChloride) (not consumed) -> C60H30 + 3 NH3
(there's also 3 C20H13N + 3 SOCl2 + 6 KOH -> C60H30 + 3 SO2 + 6 KCl + 3 NH3 + 3 H2O, but that might be too much

2021-04-08 15:47 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
>          LARGE_ENGRAVER_RECIPES.recipeBuilder()
Following from above, C60H30 + 15 O -> C60 + 15H2O, adjusting the recipe map which we will do eventually

2021-04-08 15:47 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        //  Ti + Al + Cl -> TiAlCl (treat as chem reactor)
Technically it is a mixture of TiCl4 + AlCl3

2021-04-08 20:28 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +                .fluidOutputs(SaltWater.getFluid(1000))
Marked as a pass

2021-04-08 20:35 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/ZylonChain.java
> -        CHEMICAL_RECIPES.recipeBuilder()
It is a comment, so it is of course resolved

2021-04-08 20:48 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/LithiumChain.java
>          ELECTROLYZER_RECIPES.recipeBuilder().duration(900).EUt(125)
Looks like aluminium also outputs as a dust, so we can keep this for consistency

2021-04-08 20:55 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/NuclearHandler.java
> +        // [Fuel + NO3 + H2O] + N2H4 + RP1 + C12H27O4P = Fuel2N3 + Red Oil [N2H4 + RP1 + C12H27O4P]
Left to Nuclear Rework, so marked as unresolved for the time being

2021-04-10 04:38 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // C19H14 + O -> C18H12 + CH2O
Now seems like a good time to mention that the Chemical Plant and LCR both had their item outputs increased in this PR, so this recipe you suggested fits fine in a LCR.

2021-04-10 05:15 UTC, DStrand1 commented
With the last commit, I addressed all changes requested by @pablocnvs

2021-04-10 11:53 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/SuperconductorsSMDChain.java
> +        // TiCl4 + C3H4 + C2H2 -> HCl + C5H5Cl3Ti
I actually need that to be (C5H5)2Cl2Ti for a component in the production of the ultrashort pulse laser (the photopolymer solution i think it is called)

2021-04-10 11:57 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/SuperconductorsSMDChain.java
> +        // TiCl4 + C3H4 + C2H2 -> HCl + C5H5Cl3Ti
I do need to see how this affects the photopolymer solution, if it gets too hard i won't bother with it

2021-04-15 17:01 UTC, hjae78 approved these changes

2021-04-15 17:41 UTC, pablocnvs approved these changes
I have nothing further to comment, so i'll aprove the PR.

2021-04-18 19:26 UTC, merged