Fix Missing JSON for Uranium Saturated Yarn
Gregicality/gregicality pull request #405
Opened 2021-03-15 01:10 UTC by TechLord22

This is a simple PR that adds the missing JSON model for Uranium Saturated Yarn, which previously caused it to show up as a missing texture in-game.

2021-03-15 09:39 UTC, pablocnvs approved these changes

2021-03-15 11:51 UTC, huneau requested changes
dont forget to increase the oregen file that overwrite the previsous one

2021-03-17 21:30 UTC, hjae78 commented
> dont forget to increase the oregen file that overwrite the previsous one

What do you mean? This isn't doing anything with oregen

2021-03-17 21:30 UTC, hjae78 approved these changes

2021-03-19 01:47 UTC, Yefancy approved these changes

2021-03-19 08:26 UTC, huneau approved these changes

2021-03-20 09:15 UTC, merged