Tesla tower [Not ready]
Gregicality/gregicality pull request #410
Opened 2021-03-17 13:04 UTC by brachy84

This will add the Tesla tower multiblock to Gregicality.
This marked as Not ready because it might need some balance and changes in behavior.
It is based on #352 and #158. This multiblock is intended to be gated to at least UHV.

 ### How it works:
* The multiblock looks pretty much the same as the pictures in #158 from Zalgo
* The middle coils can have height between 3 and 128
* The coil height determines the range
  currently the formula is `pow(coilHeight, 0.6) * 4`
  (7.7 blocks at height 3 and 73.5 blocks at 128)
* The coils can only be the new coils from gregicality
* The coil tier determines the Amps
* The tower will try to power machines every 10 ticks
* The tower will scan it's range for `ICoverable's` with a wireless receiver cover
* The cover itself does nothing besides telling the tower to give power
* I don't know how much lag it would cause when the tower would scan the area every second so I made a button in the gui to manually scan
* The torus can be made out of different materials (maybe the materials could have effects on effeciency and range)
* You can also power machines that are out of range or even in another dimension. To to that:
  * Take a data stick use it on a machine and put it in a input bus of the tower
  * The position and dimension will be shown in the tooltip
  * It will require qubits additionally (1 qubit/t per machine out of range)
 
The amount of energy send per pulse needs to be adjusted.
Tell me what you think and how it could be improved.

2021-03-17 13:21 UTC, huneau commented
Hum, its a huge work but I have so many things to say.
I will close #158 because its not what I want, I will enhance #352 with my spec.

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    public Predicate<BlockWorldState> torusPredicate() {
What effect do the different materials have here?

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    public Predicate<BlockWorldState> itemInputPredicate() {
This can be removed

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    }
I'm not sure if I understand this, do we feed energy to all block positions given by the data sticks and then scan for machines that have the cover and feed energy to them as well?

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +        return super.createUITemplate(entityPlayer);
Is this override needed?

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    protected final double rangeFactor = 4.0D;
This could be moved to config

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +        }
Very nice idea!

2021-03-17 13:43 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +                int qubitCost = 10;
Another config candidate

2021-03-17 13:46 UTC, hjae78 commented
Very nice work Brachy! Nice to have you back!

2021-03-17 18:38 UTC, brachy84 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    }
It scans all blocks in range for entities with the cover and puts them in the list.

The data stick is only for when your machine is out of range

2021-03-17 19:00 UTC, DStrand1 requested changes

2021-03-17 19:00 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    }
Same as above, this override is unneeded in current impl

2021-03-17 19:01 UTC, DStrand1 commented
I am changing this PR to draft instead of stating "Not Ready" in the title

2021-03-17 22:49 UTC, brachy84 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityTeslaTower.java
> +    public Predicate<BlockWorldState> torusPredicate() {
currently none. But the tower could have a default energy loss of 40%.
The blocks then could have stats like conductivity (which would decrease energy loss) and a range modifier
A maxed out tower should be made out of UXV Superconductor blocks to have 0-1% loss and maximum range.
None of these are implemented yet. Just ideas. I could also add a crafttweaker method to add torus blocks

2021-03-21 06:26 UTC, brachy84 commented
I thought about this a little more and I think I will close it. Because the tower is really op. Yeah, it's pretty cool, but not needing any cables at UHV and above is just game breaking. So I will probably close this and maybe make something that fits more what decal wants and is more balanced. Unless we find a good way to balance this.

2021-03-21 06:32 UTC, closed without merging