[Tool] Freedom Wrench
Gregicality/gregicality pull request #439
Opened 2021-04-05 17:30 UTC by Yefancy

### Freedom Wrench
An interesting tool:

- Allows the player to rotate the multiblock controller (such as sideways structure).
- Projection display the structure (reference from JEI).
- Debug mode helps check the position of the error block.

video: [youtube](https://www.youtube.com/watch?v=la4ATNYrzEo&list=PLBAo7z4aqr3-GwXkilU4BVXHDErygdvMt&index=5&ab_channel=KilaBashLiang)

### Image:
![image](https://user-images.githubusercontent.com/18493855/113603997-405c5680-9677-11eb-8280-c197fba99092.png)
![image](https://user-images.githubusercontent.com/18493855/113604165-7699d600-9677-11eb-8efa-ee506881eb6b.png)
![image](https://user-images.githubusercontent.com/18493855/113604231-8d402d00-9677-11eb-97b4-fc06c61906b2.png)

2021-04-05 18:36 UTC, hjae78 commented
Wow, just amazing work as always

2021-04-07 07:44 UTC, huneau commented
yes awesome job, the last thing it needs its a building mod like environmental tech

2021-04-07 07:56 UTC, hjae78 commented on src/main/java/gregicadditions/coremod/GAClassTransformer.java
> +                tform = RecipeMapMultiblockControllerTransformer.INSTANCE;
You reference `RecipeMapMultiblockController` a lot, does this not work for multiblocks that aren't of this instance? For example Large Miners, Drilling Rig

2021-04-07 08:12 UTC, Yefancy commented on src/main/java/gregicadditions/coremod/GAClassTransformer.java
> +                tform = RecipeMapMultiblockControllerTransformer.INSTANCE;
projection work for all `MultiblockControllerBase`. but rotation just work for `RecipeMapMultiblockController` at the present. 
After rotation, BlockPattern detection and rotation of the overlay are working well, but i have noticed that some machines may have strict requirements for `frontFacing`, which must not be facing up or down. (e.g. [Cosmic Ray Detector](https://github.com/Gregicality/gregicality/blob/5bf0eb12f3a6bf8dbb7e4627189219434e52fb00/src/main/java/gregicadditions/machines/multi/MetaTileEntityCosmicRayDetector.java#L85-L90))

2021-04-08 15:35 UTC, DStrand1 commented
At this point, I feel like at least the in-world preview should be moved up to GTCE, though it is already done by Multiblock Tweaker. Have you tested what happens with both mods installed?

2021-04-08 15:52 UTC, Yefancy commented
> At this point, I feel like at least the in-world preview should be moved up to GTCE, though it is already done by Multiblock Tweaker. Have you tested what happens with both mods installed?

- I implemented a feature similar to Multiblock Tweaker because In-World Preview is required to support freedom rotation (I got Eutro's support for this). I don't want to implement projection for GTCE, and rewrite a freedom rotation supporting one for Gregicality. It is better not to separate the two works.
- They work well together, or at least don't cause crash,

2021-04-08 16:01 UTC, DStrand1 commented
I have been wanting to implement something like MBT’s in-world preview into GTCE, so I will see if we can get this full PR into GTCE. I can assist with porting it to there if it gets approved.

2021-04-08 16:25 UTC, Yefancy commented
> I have been wanting to implement something like MBT’s in-world preview into GTCE, so I will see if we can get this full PR into GTCE. I can assist with porting it to there if it gets approved.

sure, it would be nice if it could be integrated into GTCE. I don't want to do hacking gtce all the time.

2021-04-11 03:16 UTC, DStrand1 requested changes
Rendering really isn't my thing, so my review is more focused on some logistics of this PR being merged more than anything else. Hope it isn't too annoying

2021-04-11 03:16 UTC, DStrand1 commented on src/main/java/gregicadditions/GAConfig.java
> +            public int[] scanCosts = {8, 32, 512, 2048};
Seems there are a few commits jumbled into here as a result of you needing the GTCE 1.14.0 crash fix. Since that is included in master, dropping those commits and rebasing your branch should be safe and would help to not touch files that are not part of this PR.

2021-04-11 03:16 UTC, DStrand1 commented on src/main/java/gregicadditions/coremod/transform/GTUtilityTransformer.java
> +public class GTUtilityTransformer extends ClassMapper {
The change to this class is unnecessary since I am removing it as part of #388. If possible, can you revert the change to just this class? Otherwise either this PR or the Chemistry PR will have to rebase due to this file changing in master, depending on which PR is merged first.

2021-04-11 03:34 UTC, Yefancy commented on src/main/java/gregicadditions/coremod/transform/GTUtilityTransformer.java
> +public class GTUtilityTransformer extends ClassMapper {
you are right, i noticed that this PR is a bit of a mess after rebase. i will continue to work here, but this PR will always be WIP until it is closed. after that, I will create a new branch and PR after Chemistry PR merged.

2021-04-13 07:27 UTC, closed without merging