Update zh_cn.lang
Gregicality/gregicality pull request #443
Opened 2021-04-08 15:22 UTC by Wegifan

2021-04-08 15:34 UTC, DStrand1 approved these changes

2021-04-08 15:40 UTC, Yefancy approved these changes

2021-04-08 16:11 UTC, ChromaPIE requested changes
大致没有问题，但是注意：
- 所有括号必须使用全角括号（），同时如果前后有空格请删除；
- 不清楚是否存在zh_cn和en_us行数不同步统一的情况，提一嘴以防万一，如有请修改。

2021-04-09 16:56 UTC, TechLord22 approved these changes

2021-04-14 02:16 UTC, ChromaPIE approved these changes

2021-04-14 02:17 UTC, ChromaPIE commented
Good to go if confirmed no further work needed

2021-04-15 16:49 UTC, merged