[Tool] Freedom Wrench
Gregicality/gregicality pull request #450
Opened 2021-04-14 08:37 UTC by Yefancy

Basically the same as #439 

Additional Contents:
- Central monitor can be rotated at will now
- Supporting rotation for all multi-block now. (some machines aren't perfect, but don't crash)
- Building mode: fast build (no consumption in creative mode)

GIF:
![rotation](https://user-images.githubusercontent.com/18493855/114679982-47522b80-9d3f-11eb-9a2f-3a372600f52c.gif)

![wrench](https://user-images.githubusercontent.com/18493855/114679452-bed38b00-9d3e-11eb-9244-6e6493d0cbfe.gif)

2021-04-14 09:05 UTC, hjae78 commented
Fucking amazing! Building mode finally!

2021-04-14 09:10 UTC, Yefancy commented
yeah, Decal is right that this feature is needed. Make testing in creative mode easier

2021-04-14 09:13 UTC, Zalgo239 commented
This is awesome! Will save lots of time

2021-04-14 13:49 UTC, htmlcsjs commented
Let's fucking go

2021-04-18 19:15 UTC, hjae78 approved these changes

2021-04-28 01:18 UTC, DStrand1 requested changes
A lot of this code is rendering and packet handling, most of which is hard to review just from code and I haven't found errors in testing so I will trust it. However, has this been tested on a dedicated server instance? I have some concerns about certain sections, especially in `FreedomWrenchBehavior` not testing for client or server instance everywhere it should be. Other than that, I think this is ready to go

2021-04-28 01:18 UTC, DStrand1 commented on src/main/java/gregicadditions/item/behaviors/FreedomWrenchBehaviour.java
> +                            player.sendMessage(new TextComponentString("Spin: " + (next == EnumFacing.NORTH ?
I think these should be moved to translation keys, and it can simply be changed from `TextComponentString` to `TextComponentTranslation`. There are a few below this as well. With this change, I think this needs to be within a `world.isRemote` check, though it may need one even without the change

2021-04-28 01:41 UTC, Yefancy commented on src/main/java/gregicadditions/item/behaviors/FreedomWrenchBehaviour.java
> +                            player.sendMessage(new TextComponentString("Spin: " + (next == EnumFacing.NORTH ?
thanks for your review. i have test it on a dedicated server instance before, and it works well. `FreedomWrenchBehavior` do side checking [here](https://github.com/Gregicality/gregicality/pull/450/files/8c49694f695858944423bae184f9777c2294adab#diff-2c8c8977a3f6d21fd5422accd4a1a931f9c36ae250724007165d6b1ddac5b18aR43). 

ill add translation keys later

2021-04-28 07:44 UTC, merged