Steam chunk miner, chunk miner overlays, steam machine tweaks
Gregicality/gregicality pull request #492
Opened 2021-05-20 00:48 UTC by Puzzlebark

This PR contains 4 changes, 3 of which have to do with steam machines and 1 cosmetic addition:
- A new steam chunk miner that performs one mining operation every 8 ticks and requires 16mb/t of steam. The expensive recipe as well as the setup required to get good use out of it are the tradeoff for having early auto-mining, but it is subject to change with feedback.

![image](https://user-images.githubusercontent.com/45017038/118902139-878b6780-b904-11eb-8029-7cdb6dc3939c.png)

- The steam mixer's input slots can now transfer fluid to and from containers.

- The steam macerator recipes have been reverted to using diamonds instead of flint.

- Electric chunk miners have new overlay textures on their horizontal faces. 

![image](https://user-images.githubusercontent.com/45017038/118902370-0aacbd80-b905-11eb-84b0-7ae0efce7d12.png)

2021-05-20 03:50 UTC, DStrand1 requested changes
The functionality of this is great! I'm surprised at how well you were able to get the Fluid Handler item slot to work, properly delegating Steam and Drilling Fluid into the right internal fluid tanks. There are just a few places in the code I would like to see cleaned up

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/Miner.java
> +        STEAM(8, 1, 0, "", 1),
This is probably fine, but it is bad practice to insert values into an Enum anywhere but the end, as this changes their ordinals. I looked and saw no places where this is a problem, but if you could sanity check this and make sure that `ordinal()` or `values()` is not called on this Enum, that would be great.

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +import net.minecraftforge.fluids.FluidTank;
There are some extraneous imports in here

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +    private final ItemStackHandler fluidContainerInventory;
This needs to be saved in `writeNBT` and `readNBT` or else items in the Fluid Container slots will be voided when the machine is unloaded

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +            }
```suggestion
            if ((importFluids.getTankAt(0).getFluidAmount() < 1) || (importFluids.getTankAt(1).getFluidAmount() < 16)) {
                return;
            }
```

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/categories/machines/SingleblockCraftingRecipes.java
> +        ModHandler.addShapedRecipe("ga_steam_macerator_steel",  MetaTileEntities.STEAM_MACERATOR_STEEL.getStackForm(),  "DXD", "XMX", "PXP", 'M', MetaBlocks.MACHINE_CASING.getItemVariant(BlockMachine
Instead of updating these, you can simply remove the recipe removals and additions

2021-05-20 03:50 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +
The items in the Fluid Container slots are voided if the machine is broken. This section of code will fix that (you will have to import `net.minecraft.block.Block`):
```suggestion

        @Override
        public void onRemoval() {
            for (int slot = 0; slot < fluidContainerInventory.getSlots(); slot++)
                Block.spawnAsEntity(getWorld(), getPos(), fluidContainerInventory.getStackInSlot(slot));
        }

```

2021-05-20 03:53 UTC, DStrand1 commented
Also I asked for the Steam Macerator changes to be in this PR, and @TechLord22 asked for the Steam Mixer fluid slot changes, so that is why 2 seemingly unrelated changes are here.

2021-05-20 18:59 UTC, Puzzlebark commented on src/main/java/gregicadditions/machines/multi/miner/Miner.java
> +        STEAM(8, 1, 0, "", 1),
I'll keep this in mind in the future. Neither of those methods seem to be called on this Enum.

2021-05-20 19:00 UTC, Puzzlebark commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +import net.minecraftforge.fluids.FluidTank;
Got it, the redundant imports have been removed.

2021-05-20 19:05 UTC, Puzzlebark commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +            }
My bad, forgot to remove that before opening the PR haha

2021-05-20 19:18 UTC, Puzzlebark commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +
Good catch, that's been added now.

2021-05-20 20:31 UTC, Puzzlebark commented on src/main/java/gregicadditions/machines/multi/miner/TileEntitySteamMiner.java
> +    private final ItemStackHandler fluidContainerInventory;
Got that implemented.

2021-05-21 04:02 UTC, DStrand1 approved these changes

2021-05-21 19:32 UTC, DStrand1 commented
In further Discord discussion, we realized that this machine is not consistent with other Steam machines with its output slot. It should vent Steam for each broken block, and not have item output capabilities. Additionally if it is unable to vent, the machine should stop like other Steam machines

2021-05-23 00:47 UTC, Puzzlebark commented
The output face has now been replaced with an exhaust face.

2021-05-23 04:21 UTC, DStrand1 commented
Seems there is a lot of older commits coming along with this PR. If you do an interactive rebase, you can clean that up.

`git rebase -i HEAD~<some number of commits>`
for example, `git rebase -i HEAD~20`. Then you will be able to pick and choose which commits you want to keep

2021-05-23 05:05 UTC, Puzzlebark commented
Fixed.

2021-05-31 18:47 UTC, Puzzlebark commented
The steam miner no longer responds to right-clicking with a wrench. All the issues with the steam miner I'm aware of have been addressed.

2021-06-02 16:54 UTC, TechLord22 approved these changes

2021-06-04 07:50 UTC, merged