Add Double Plates and Delete Double Ingots
Gregicality/gregicality pull request #497
Opened 2021-05-20 23:16 UTC by bruberu

This particular PR does as the title says.
This does make a config option obsolete, and potentially deletes double ingots from worlds, although I must say that I don't believe that most people just keep them around.

2021-05-21 04:06 UTC, DStrand1 requested changes
Just a couple small things, otherwise I think this PR is great! Will really help balance out  turbine blades and battery tower cells, and other things in the future

2021-05-21 04:06 UTC, DStrand1 commented on src/main/java/gregicadditions/GAMaterials.java
> +    static long CORE_METAL = EXT2_METAL | GENERATE_RING | GENERATE_FRAME | GENERATE_ROTOR | GENERATE_SMALL_GEAR | GENERATE_DENSE | GENERATE_DOUBLE_PLATE;
The flag only needs to be applied to EXT2_METAL since CORE_METAL already contains all the flags of EXT2_METAL
```suggestion
    static long CORE_METAL = EXT2_METAL | GENERATE_RING | GENERATE_FRAME | GENERATE_ROTOR | GENERATE_SMALL_GEAR | GENERATE_DENSE;
```

2021-05-21 04:06 UTC, DStrand1 commented on src/main/java/gregicadditions/item/GAMetaItem.java
> -                GAConfig.GT6.addDoubleIngots ? GAEnums.GAOrePrefix.ingotDouble : null,
We may as well put the double plate prefix here so that if players do happen to have a double ingot for some material, it will get converted to a double plate

2021-05-21 19:31 UTC, DStrand1 approved these changes

2021-05-22 02:54 UTC, TechLord22 approved these changes
Nice work!

2021-05-24 03:56 UTC, bruberu commented
Note: I fixed the bug with compressor recipes registering for the wrong items (e.g. chests) within the latest release, as I don't really know how to manage multiple PRs yet, but it should still be a useful thing to have here.

2021-05-24 18:04 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/categories/CasingRecipes.java
> +                .buildAndRegister();
I'm a little hesitant about buffing this recipe so much. Compared to the corresponding batteries the cells are much cheaper

2021-05-24 18:07 UTC, merged

2021-05-24 18:07 UTC, bruberu commented on src/main/java/gregicadditions/recipes/categories/CasingRecipes.java
> +                .buildAndRegister();
Considering that making these batteries functional requires one making at least 36 of these, I personally believe that this would make the recipes considerably less painful to deal with in batches. Besides, some of the gases are already not terribly easy to get in bulk, so this should be balanced enough.