Update Multiblocks and Move to Non-Autogenerated Casings
Gregicality/gregicality pull request #507
Opened 2021-05-24 21:48 UTC by TechLord22

This PR will change the multiblock casings to individual blocks, which should improve performance for some users, as well as add new mechanics and structures to our existing multiblocks.

2021-06-06 12:05 UTC, Yefancy commented on src/main/java/gregicadditions/coremod/transform/MetaTileEntityTransformer.java
> +            } else if (name.equals("<preInit2>")) {
I'm not sure if this is modified by automatic way.

2021-07-02 03:20 UTC, DStrand1 requested changes
Not finished, but some review comments

2021-07-02 03:20 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/miner/MetaTileEntityLargeMiner.java
> +        FluidStack drillingMud = GAMaterials.DrillingMud.getFluid(type.drillingFluidConsumePerTick);
Was this supposed to change to Drilling Mud?

2021-07-02 03:20 UTC, DStrand1 commented on src/main/java/gregicadditions/machines/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
> +    }};
These should maybe be in a helper class?

2021-07-02 05:58 UTC, DStrand1 commented
The game will crash with an `ArrayOutOfBoundsException` if `highTierExtruders` is disabled, because it tries to call `MetaTileEntities.EXTRUDER[EV - 1]`, which will become index 3. However since GTCE has no LV extruder, the `EXTRUDER` array does not have an index of 3. We need to change this indexing to `EV - 2`

2021-07-02 12:50 UTC, hjae78 commented on src/main/java/gregicadditions/item/GAHeatingCoil.java
> +        HEATING_COIL_5("heating_coil_5", 14200, 128, 32, null);
What about Cosmic Neutronium for the last one?

2021-07-02 12:55 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/GABoostableWorkableHandler.java
> +                int durationModified = (int) (duration * maintenanceDurationMultiplier);
Okay this looks really wonky to me. The method indicates that we're returning the amount of fuel but the we're returning variables called duration. Furthermore this to me seems like the more maintenance problems we have the longer the fuel will last? Am I just stupid or am I reading that correctly?

2021-07-02 12:55 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/GAFuelRecipeLogic.java
> +                System.out.println("numMaintenanceProblems " + numMaintenanceProblems);
Remove

2021-07-02 13:00 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/multiblockpart/MetaTileEntityMufflerHatch.java
> +            pollutionParticles();
We got a report about this call crashing on servers since the method is annotated to be client side only, I tried moving these lines into the remote check above but it didn't seem to change it. This requires further investigation. Also I noticed that no particles appeared for me, could be because of me having particles set to minimal but just wanted to double check if that's intended.

2021-07-02 13:02 UTC, hjae78 commented on src/main/java/gregicadditions/materials/SimpleDustMaterial.java
> +
This is still a relevant TODO imo.

2021-07-02 13:10 UTC, hjae78 requested changes
I've made a number of comments that I feel need to be addressed before we can merge this. Furthermore I worry that the maintenance/muffler feature is not something everybody desires. To resolve this and also offer more customizability I think we should move the `minimumMaintenanceTime` to config.

2021-07-02 13:12 UTC, hjae78 commented on src/main/java/gregicadditions/machines/multi/multiblockpart/MetaTileEntityMaintenanceHatch.java
> +                }
I don't understand why we're doing this, why don't we just store tape in the maintenance hatch?

2021-07-08 22:11 UTC, pablocnvs commented on src/main/java/gregicadditions/fluid/GAMetaFluids.java
> +                    && mat.chemicalFormula.length() > 2) {
Is there a reason to exclude single element materials here?

2021-07-08 22:12 UTC, pablocnvs commented on src/main/java/gregicadditions/item/GAHeatingCoil.java
> +        HEATING_COIL_5("heating_coil_5", 14200, 128, 32, null);
We do need more materials in those tiers. Not saying cosmic neutronium is bad, just making it the only material feels weird.

2021-07-08 22:43 UTC, pablocnvs commented on src/main/java/gregicadditions/machines/multi/GABoostableWorkableHandler.java
> +                int durationModified = (int) (duration * maintenanceDurationMultiplier);
I think you're not alone. Maybe more docs could clarify this but otherwise i'd say it is pretty wonky

2021-07-16 05:58 UTC, TechLord22 commented on src/main/java/gregicadditions/fluid/GAMetaFluids.java
> +                    && mat.chemicalFormula.length() > 2) {
Single element materials are excluded here, since materials with one element means that they are pure. An example of this would be aluminium. Alloy blasting things that aren't compounds with more than one component isn't the intention of the alloy blast furnace, as its name states it's intention for alloying instead of just smelting.

2021-07-16 05:59 UTC, TechLord22 commented on src/main/java/gregicadditions/item/GAHeatingCoil.java
> +        HEATING_COIL_5("heating_coil_5", 14200, 128, 32, null);
For now I'll use Cosmic Neutronium. If we come up with a better material at a later date, we can switch it then.

2021-07-16 06:00 UTC, TechLord22 commented on src/main/java/gregicadditions/machines/multi/GABoostableWorkableHandler.java
> +                int durationModified = (int) (duration * maintenanceDurationMultiplier);
I think I copied and modified the wrong method here. I made some changes to the regular GAFuelLogic class to properly take into account maintenance, instead of doing it in here.

2021-07-16 14:48 UTC, TechLord22 commented on src/main/java/gregicadditions/machines/multi/multiblockpart/MetaTileEntityMufflerHatch.java
> +            pollutionParticles();
I added a `getWorld.isRemote()` check here. I'm reasonably confident that should fix the crash. As for the particles, I can confirm the Minimal particle setting does turn them off. The particles themselves are generated through vanilla code, so I assume the vanilla `SMOKE_LARGE` particle we use is bound to that setting. I think that's fine to disable the particles with that setting as well, since it is there for performance reasons to begin with.

2021-07-24 16:30 UTC, htmlcsjs requested changes
Looks good from a gameplay standpoint apart from:
 - Mega Blast Furnace didnt work for me
 - The Drilling Plants dont have JEI pages

2021-07-24 17:37 UTC, pablocnvs approved these changes
Amazing job, the new shapes look refreshing and will surely make stuff more lively with all these additions. Of course a refactor needs to be done to take into account the latest pr, but other than that we should be able to go ahead.

2021-07-25 01:08 UTC, ALongStringOfNumbers requested changes
An in progress review, which I will have to finish later.

Just checking over code really, an not much in game.

2021-07-25 01:08 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/recipes/CasingConvesion.java
> +public class CasingConvesion {
This should be spelled correctly as `CasingConversion`

2021-07-25 01:08 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/recipes/GARecipeMaps.java
> +                .duration(1).EUt(375000)); // UV-tier, 1tick processing time
If the recipes were changed to UV tier, the JEI preview for the multiblock should have the energy hatch swapped from UHV tier to UV tier.

2021-07-25 18:39 UTC, TechLord22 commented on src/main/java/gregicadditions/jei/multi/ChemicalPlantInfo.java
> +                        .where('X', MetaBlocks.METAL_CASING.getState(BlockMetalCasing.MetalCasingType.STEEL_SOLID))
The doubling of the casing stacks is actually a bug with GTCE. I'll fix the maintenance problem regardless.

2021-07-25 18:51 UTC, TechLord22 commented on src/main/java/gregicadditions/machines/energy/TileEntityLargeTransformer.java
>              if (output.getEnergyStored() < output.getEnergyCapacity()) {
When messing with this multiblock originally, I encountered some extreme FPS lag depending on what minor changes I made. The multiblock works well for right now, and a future performance and/or logic improving PR should be done in the future in my opinion.

2021-07-25 18:53 UTC, TechLord22 commented on src/main/java/gregicadditions/machines/multi/MetaTileEntityBatteryTower.java
> +                .where('X', statePredicate(getGlassState()).or(statePredicate(getCasingState())).or(abilityPartPredicate(ALLOWED_ABILITIES)))
People could always place any allowed ability in the glass, this change allowed them to make the multi more visually consistent by using casings instead of glass. The casings are more expensive than the glass too, so I say it's fine to give people the option. I don't see the need to change the original functionality.

2021-07-25 19:43 UTC, htmlcsjs requested changes
Looks good, one change i would like is the drilling plants JEI info to have the correct voltage input hatch

2021-07-25 21:02 UTC, ALongStringOfNumbers requested changes
Another Partial review coming in. 

Some general points mentioned in the review:
- Multiblock controllers should face the player when they first open up the multiblock preview
- Component blocks should have tooltips added to them saying they limit the tier of the multiblock, and need to be upgraded to higher tiers
- The `getDescription` method for multiblock info pages should never return an empty string, as that causes issues with JEI. It should at least return "Temporary Placeholder".

2021-07-25 21:59 UTC, TechLord22 commented on src/main/java/gregicadditions/jei/multi/advance/LargeNaquadahReactorInfo.java
> +                .aisle("#CMC#", "#CSC#", "#CCC#", "##C##", "##C##", "#CCC#", "#CGC#", "#CCC#")
We should not remove the single blocks. The single blocks that some people (not myself) do not like are the ones that take item inputs. Ours take fluids, and should definitely stay.

2021-07-25 23:22 UTC, TechLord22 commented on src/main/java/gregicadditions/jei/multi/override/CrackerUnitInfo.java
> -            if (!Arrays.asList(GAConfig.multis.heatingCoils.gregicalityheatingCoilsBlacklist).contains(coilType.getName())) {
It is intended. Going beyond the GTCE coils made all multiblocks that could support them (excluding blast furnaces) too strong. The bonuses got very ridiculous at the second gregicality coil, so I felt it was best for the coils to be exclusive to temperature based multiblocks.

2021-07-25 23:24 UTC, TechLord22 commented on src/main/java/gregicadditions/jei/multi/override/ElectricBlastFurnaceInfo.java
>  						.where('E', MetaTileEntities.ENERGY_INPUT_HATCH[GAValues.MV], EnumFacing.EAST)
Currently there are both import and export fluid hatches in the preview. Can you elaborate on what needs to be changed here specifically?

2021-07-25 23:29 UTC, TechLord22 commented on src/main/java/gregicadditions/jei/multi/simple/LargeMultiUseInfo.java
>  					.where('R', GAMetaBlocks.ROBOT_ARM_CASING.getDefaultState())
This machine is being removed (staged) as of this PR, so I think it's fine to leave them without a tooltip.

2021-07-27 13:58 UTC, htmlcsjs requested changes
Looks good from gameplay standpoint, i would like you to look at my comments though

2021-07-27 13:58 UTC, htmlcsjs commented on src/main/java/gregicadditions/GAConfig.java
>              public String[] gtceHeatingCoilsBlacklist = new String[]{
I think the suggested default should be a default, as fusion coils have a higher tempreture than titan steel and are avalible earlier

2021-07-27 18:23 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/override/ElectricBlastFurnaceInfo.java
>  						.where('E', MetaTileEntities.ENERGY_INPUT_HATCH[GAValues.MV], EnumFacing.EAST)
In the preview for the Gregicality coils, there are two fluid imports, while for the GTCE coils it was changed to 1 fluid import, 1 fluid export

2021-07-27 20:05 UTC, ALongStringOfNumbers requested changes
Another in progress review.

General points:
- Multiblocks with the description "Temporary Placeholder" should get an actual description
- There are some multiblocks missing the component casing tooltips
- There are some multiblocks that need to be rotated
- Multiblocks with a minimum casing amount should have that amount added as a tooltip. These will have to be hardcoded because the criteria is not accessible.

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/machines/multi/advance/hyper/MetaTileEntityHyperReactorI.java
> +                .where('C', statePredicate(getCasingState()).or(abilityPartPredicate(MultiblockAbility.OUTPUT_ENERGY, MultiblockAbility.IMPORT_FLUIDS, GregicAdditionsCapabilities.MAINTENANCE_HATCH)))
Could just make an allowed abilities field

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeWiremillInfo.java
> +					.where('M', GAMetaBlocks.MOTOR_CASING.getDefaultState());
Needs casing tooltip

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeWiremillInfo.java
>  		return Lists.newArrayList(shapeInfo);
Needs a description

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeWiremillInfo.java
> +					.where('H', GATileEntities.MAINTENANCE_HATCH[0], EnumFacing.SOUTH)
Needs to be rotated to face the player

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeThermalCentrifugeInfo.java
>                      .where('S', GATileEntities.LARGE_THERMAL_CENTRIFUGE, EnumFacing.SOUTH)
Needs to be rotated to face the player

2021-07-27 20:05 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeThermalCentrifugeInfo.java
>          return Lists.newArrayList(shapeInfo);
Needs a description

2021-07-27 23:50 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/MiscRecipes.java
> +                .output(dust, TinAlloy, 2)
The purpose of these is to mirror the alloy smelter recipes. Mixer and alloy blast recipes for every material are something many people desired, so mirroring the alloy smelter recipes was the best course of action in my opinion.

2021-07-28 18:21 UTC, ALongStringOfNumbers requested changes
Barely got started on this review before I had to take a break, but I have condensed all the multiblocks that still need descriptions

To condense everything, the multiblocks that currently need descriptions are:

Large Bending and Forming
Fusion Reactor 4
Alloy Blast Furnace
Cosmic Ray detector
Drilling Rig
Bio Reactor
Void Miner 1
Void Miner 2
Void Miner 3
Gas Centrifuge
Large Chemical Reactor
Large Cutting Machine
Large Electrolyzer
Large Extruder
Large Macerator
Large Mixer
Large Multi use
Large Packager

2021-07-28 18:21 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/AssemblyLineInfo.java
> +			builder.aisle("FIC", "RTR", "GSG", "#Q#");
The structure is not formed in the JEI preview

2021-07-28 18:21 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/PlasmaCondenserInfo.java
> +        this.addBlockTooltip(GAMetaBlocks.METAL_CASING_1.getItemVariant(MetalCasing1.CasingType.HASTELLOY_N), casingTooltip);
The Pump component blocks need tooltips as well

2021-07-28 18:21 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/advance/BioReactorInfo.java
>          return new String[] {"Temporary Placeholder"};
Needs a description

2021-07-28 18:21 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/advance/BioReactorInfo.java
> +
Needs component block tooltips

2021-07-29 12:05 UTC, htmlcsjs commented on src/main/java/gregicadditions/GAConfig.java
>              public String[] gtceHeatingCoilsBlacklist = new String[]{
Im going to resolve this as its been fixed to my understanding

2021-08-06 05:59 UTC, ALongStringOfNumbers requested changes

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +        int numMaintenanceProblems = (this.metaTileEntity instanceof GARecipeMapMultiblockController) ?
This should also check for if the mte is a `QubitRecipeMapMultiblockController` with `hasMaintenance` set to true

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +        if (metaTileEntity instanceof GARecipeMapMultiblockController) {
Needs a check for `QubitRecipeMapMultiblockController` now as well

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +            GARecipeMapMultiblockController controller = (GARecipeMapMultiblockController) metaTileEntity;
Same, needs a check for the Qubit controller as well

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeArcFurnaceInfo.java
> +        return new String[]{};
missed description

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/AdvancedChemicalReactorInfo.java
> +		return new String[]{"Must have at least 22 chemically inert casings to form!"};
ideally this should be a localized comment

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/jei/multi/simple/LargeBreweryInfo.java
> +        return new String[]{};
Should have a description

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/machines/multi/GAFuelRecipeLogic.java
> +                        }
Needs to call tryAcquireNewRecipe if the multiblock is an instance of a Fueled multiblock, but does not have maintenance.

```suggestion
                        } else {
                             this.tryAcquireNewRecipe();
                        }
```

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/machines/multi/GAFueledMultiblockController.java
> +            if (maintenanceHatch.getType() == 2) {
This should have a config check for enabled maintenance

2021-08-06 05:59 UTC, ALongStringOfNumbers commented on src/main/java/gregicadditions/machines/multi/GAMultiblockWithDisplayBase.java
> +            if (maintenanceHatch.getType() == 2) {
This should have a config check for enabled maintenance

2021-08-06 23:27 UTC, TechLord22 commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +        int numMaintenanceProblems = (this.metaTileEntity instanceof GARecipeMapMultiblockController) ?
This shouldn't be necessary as `QubitRecipeMapMultiblockController` class extends `GAMultiblockRecipeLogic`. All machines extending the GA class technically have maintenance values still. They are always set to fully repaired unless `hasMaintenance` is true, so nothing extra should need to be done here.

2021-08-06 23:28 UTC, TechLord22 commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +        if (metaTileEntity instanceof GARecipeMapMultiblockController) {
This shouldn't be necessary as QubitRecipeMapMultiblockController class extends GAMultiblockRecipeLogic. All machines extending the GA class technically have maintenance values still. They are always set to fully repaired unless hasMaintenance is true, so nothing extra should need to be done here.

2021-08-06 23:28 UTC, TechLord22 commented on src/main/java/gregicadditions/capabilities/impl/GAMultiblockRecipeLogic.java
> +            GARecipeMapMultiblockController controller = (GARecipeMapMultiblockController) metaTileEntity;
This shouldn't be necessary as QubitRecipeMapMultiblockController class extends GAMultiblockRecipeLogic. All machines extending the GA class technically have maintenance values still. They are always set to fully repaired unless hasMaintenance is true, so nothing extra should need to be done here.

2021-08-06 23:34 UTC, TechLord22 commented on src/main/java/gregicadditions/machines/multi/GAFueledMultiblockController.java
> +            if (maintenanceHatch.getType() == 2) {
This shouldn't be necessary as `GAFuelRecipeLogic` class is exclusively used with multiblocks extending `GARecipeMapMultiblockController`. All machines extending the GA class technically have maintenance values still. They are always set to fully repaired unless `hasMaintenance` is true, so nothing extra should need to be done here.

2021-08-07 15:34 UTC, htmlcsjs approved these changes
Looks good from gameplay standpoint, apart from things others have brang up

2021-08-07 21:00 UTC, DStrand1 approved these changes

2021-08-09 09:14 UTC, merged