Exotic Circuits
Gregicality/gregicality pull request #525
Opened 2021-06-08 14:30 UTC by Zalgo239

+Added Exotic circuits
+Added crafting chains for Exotic circuits
+Added localization for Exotic circuits

2021-06-08 18:03 UTC, pablocnvs reviewed
Feels pretty good, there is only one step that i can't comprehend (maybe i should've known since that happens with my own charts) and, most importantly, it is imbalanced and not knowing the step you chose makes it difficult to balance.
Overall though, i don't see anything problematic

2021-06-08 18:03 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
Can you explain in more detail this step?

2021-06-08 18:12 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
I think the issue here is the Dimethoxyethane, IRL Lithium Cyclopentadienide is usually handled as a THF solution, Dimethoxyethane is an alternative to THF. It's not consumed in the reaction itself, it's just meant to be a solvent.

2021-06-08 21:37 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
But if that is the case, why did you use cyclooctadiene?

2021-06-08 21:56 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
Yes it's meant to be cyclopentadienide, I'll fix it tomorrow

2021-06-09 00:05 UTC, DStrand1 requested changes

2021-06-09 00:05 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/RecipeHandler.java
> +        ExoticComponents.init();
Super minor, but `ExoticComponents.init()` should be called in `CircuitComponentRecipes.init()`. I left a code stub for you to add it right there :P

2021-06-09 00:05 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/categories/circuits/CircuitRecipes.java
>              fluidStack.amount = Math.min(64000, fluidStack.amount * 4);
```suggestion
            FluidStack fluidStackx4 = new FluidStack(fluidStack.getFluid(), Math.min(64000, fluidStack.amount * 4));
```
This is necessary for the soldering fluid bug to not return, where soldering fluids take insane amounts of fluid due to updating a pointer. Make sure to update the use below at line 998.

2021-06-09 00:05 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +public class QuantumDotsChain {
Another minor thing, but I think it makes more sense for this to be a method inside of `VariousChains` since it is only 5 recipes, unless you anticipate more recipes being added to this file later on

2021-06-09 07:16 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +public class QuantumDotsChain {
I thought about it too, the reason why I kept them in a separate class is that Quantum Dots have a bunch of applications I find interesting, they can be used as dyes, in LEDs, displays, solar cells, in the production of solar fuels, and have a bunch of other applications, I believe these could be of interest to us.

2021-06-09 11:45 UTC, closed without merging