Exotic Circuits
Gregicality/gregicality pull request #528
Opened 2021-06-09 11:46 UTC by Zalgo239

+Added Exotic Circuits, Components, and relevant chains
+Added English localization for exotic circuits, components, and relevant chemicals

2021-06-10 16:15 UTC, hjae78 commented on src/main/java/gregicadditions/item/GAMetaItem.java
> +        EXOTIC_MAINFRAME = addItem(608, "circuit.mainframe.exotic").setUnificationData(OrePrefix.circuit, UMV);
You should change the prefixes for Cosmic circuits

2021-06-10 16:19 UTC, hjae78 commented
Recently we nerfed a lot of EU/t but what I'm seeing here is a bit low. I'm completely fine with pretty much every step in a chain having a voltage several tiers below where it's needed but I would like to see the final step at least take a significant EU/t

2021-06-10 16:22 UTC, Zalgo239 commented
> 
> 
> Recently we nerfed a lot of EU/t but what I'm seeing here is a bit low. I'm completely fine with pretty much every step in a chain having a voltage several tiers below where it's needed but I would like to see the final step at least take a significant EU/t

What value are you thinking of?

2021-06-10 16:23 UTC, Zalgo239 commented on src/main/java/gregicadditions/item/GAMetaItem.java
> +        EXOTIC_MAINFRAME = addItem(608, "circuit.mainframe.exotic").setUnificationData(OrePrefix.circuit, UMV);
Forgot about them when dealing with the computer trouble, will change immediately

2021-06-10 16:26 UTC, Zalgo239 commented on src/main/java/gregicadditions/item/GAMetaItem.java
> +        EXOTIC_MAINFRAME = addItem(608, "circuit.mainframe.exotic").setUnificationData(OrePrefix.circuit, UMV);
I'll also change the Supra-Causal ones

2021-06-10 16:30 UTC, hjae78 commented
> > Recently we nerfed a lot of EU/t but what I'm seeing here is a bit low. I'm completely fine with pretty much every step in a chain having a voltage several tiers below where it's needed but I would like to see the final step at least take a significant EU/t
> 
> What value are you thinking of?

[These](https://github.com/Gregicality/gregicality/pull/528/files#diff-07d8bcee1a15e02ef3f2e7d6404f03814b825f03f4762824a6ea0272c1df8671R105-R126), [these](https://github.com/Gregicality/gregicality/pull/528/files#diff-07d8bcee1a15e02ef3f2e7d6404f03814b825f03f4762824a6ea0272c1df8671R160-R170), [this](https://github.com/Gregicality/gregicality/pull/528/files#diff-f7602cb8aaec8fb4878e358f51a5c323ce7b66ebe3bf0424ab36036d5aaf49f6R50-R55) and [this](https://github.com/Gregicality/gregicality/pull/528/files#diff-a67b14fa01f2b165dcd3672284173d938e54ad30944f8c2f5c3148a08331f986R44-R49)

2021-06-10 16:55 UTC, TechLord22 requested changes
I like this chain a lot, be sure to increase the EUt on a lot of these recipes, especially for the components going directly into the circuits.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final SimpleFluidMaterial Soap = new SimpleFluidMaterial("soap", 0xFFAE42);
Maybe give this a "?" for the chemical formula?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final SimpleFluidMaterial QuantumDots = new SimpleFluidMaterial("quantumdots", 0xff0000);
We have a way to make tooltips rainbow colored (parameter). Might be cool to give this some gibberish formula and have it be rainbow, since I think you said they can be used as dyes somehow.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/item/GAMetaItem.java
> +        EXOTIC_MAINFRAME = addItem(608, "circuit.mainframe.exotic").setUnificationData(OrePrefix.circuit, UMV);
Supra-Causal should also be shifted such that the mainframe is MAX tier.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                    .input(wireFine, Pikyonium)
Maybe bump the fine wire count to 4?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        ASSEMBLER_RECIPES.recipeBuilder().duration(160).EUt(5000).fluidInputs(Zylon.getFluid(72))
The EUt for the actual SMD components can definitely be increased to something much more than 5k.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .notConsumable(lens, Diamond)
I think we've actually run out of lens colors. Will this recipe conflict with other wafers?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .fluidInputs(Lubricant.getFluid(1))
Though stupid, this recipe should probably have variants for Water, Distilled Water, and Lubricant for consistency purposes.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        BLAST_RECIPES.recipeBuilder().duration(1800).EUt(120)
Should comment chemical reactions for future reference. This one I assume is `2H + 2IrO2 -> Ir2O3 + H2O`?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .fluidInputs(FullerenePolymerMatrix.getFluid(10))
I'd suggest changing this fluid to 18mB to make it more friendly ingot wise.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(240).EUt(2000)
I'd suggest a mixer for this step.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .fluidOutputs(IridiumTrichlorideSolution.getFluid(12000))
According to Mixer "rules", this would ideally output 6000mB, the recipes using this fluid can have it's usage adjusted accordingly, if you think it's necessary. If you'd like to keep the output at 12000, it is probably best to increase the HCl to 12000mB as well.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(8000)
More chemical reaction comments. `2CH4O -> CH3OCH3 + H2O`. If you don't want to output the H2O (which you are currently missing), use a dehydrator and void it through that.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
`CH3OCH3 + C2H4O -> C4H10O2`

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
What is the correct reaction for this?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        BLAST_RECIPES.recipeBuilder().duration(1800).EUt(120)
Assuming `2H + 2CfO2 -> Cf2O3 + H2O`

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(240).EUt(2000)
`6HCl + Cf2O3 -> 2CfCl3 + 3H2O`

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
What is the correct reaction for this?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .input(dust, Salt, 1)
Should this be 2 salt for mol purposes, or is 1 correct?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .output(dust, Salt, 1)
Should this be 2 salt for mol purposes, or is 1 correct?

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
`3C8H18 + P -> 3H + C24H51P`

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .fluidOutputs(Hydrogen.getFluid(300))
This should be `3000`, not `300`.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .fluidInputs(Trioctylphosphine.getFluid(100))
This should be `1000` instead of `100`.

2021-06-10 16:55 UTC, TechLord22 commented on src/main/resources/assets/gtadditions/lang/en_us.lang
>  ##cosmic
Make sure to adjust the circuit tier tooltips for the cosmic and supra-causal circuits.

2021-06-10 17:08 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .notConsumable(lens, Diamond)
It's the only one with Rutherfordium and diamond lens

2021-06-10 17:21 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
C5H6 + LiC4H9 -> LiC5H5 + C4H10

The Dimethoxyethane doesn't participate in the reaction but is a necessary solvent

2021-06-10 17:24 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        BLAST_RECIPES.recipeBuilder().duration(1800).EUt(120)
Yes it is

2021-06-10 17:28 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/OrganometallicChains.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(160).EUt(2000)
Should be 3LiC5H5 + CfCl3 -> CfC15H15 + 3LiCf

2021-06-10 17:36 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .input(dust, Salt, 1)
The salt here isn't really reacting, it's drawing the glycerol out of the soap, this would make more sense in a mixer but I had to put it in a chemical reactor due to the mixer not having two fluid outputs

2021-06-10 17:37 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/chain/QuantumDotsChain.java
> +                .output(dust, Salt, 1)
This is the salt, which had been left in the deglycerated soap from the recipe above ,being extracted when dehydrating it

2021-06-10 18:12 UTC, TechLord22 approved these changes

2021-06-10 18:12 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +                .inputs(IridiumTrioxide.getItemStack(3))
If Iridium Trioxide is Ir2O3, this should be 5 dust.

2021-06-10 18:12 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        CUTTER_RECIPES.recipeBuilder().duration(480).EUt(2000)
If I remember correctly, at least one step of a wafer usually required the player to upgrade an engraver or cutter. Perhaps one or more of the steps in the creation of the Exotic Wafer could have its EUt significantly increased.

2021-06-10 22:27 UTC, Zalgo239 commented on src/main/java/gregicadditions/recipes/categories/circuits/components/ExoticComponents.java
> +        CUTTER_RECIPES.recipeBuilder().duration(480).EUt(2000)
I'll bump them up to UV or UHV tier

2021-06-11 05:47 UTC, TechLord22 approved these changes

2021-06-12 01:36 UTC, DStrand1 approved these changes

2021-06-17 20:59 UTC, merged