Dye Rebalancing
Gregicality/gregicality pull request #539
Opened 2021-06-19 23:45 UTC by pablocnvs

This pr adresses the dreaded Dye Chain. The aim of it is to adjust all recipes to make them chemical balanced, and also boost the output of the many minichains within the Dye Chain.

2021-06-20 21:30 UTC, pablocnvs commented
In the commit comment i said loops are unavoidable, that is far from the case. Everything is truly balanced( besides some water that is voided, but water shouldn't be a problem and also water is produced in so many reactions i think the fluid dye chain could be an appropiate name)

2021-06-21 01:57 UTC, DStrand1 requested changes
At the beginning of the file, you stated:
```
Organic Dyes will use half the amount of dust per mol as the
mol convention would dictate for solids
```
However, I disagree with this, and pointed out ways that we could go about not needing to do this, since it was only in a few places that this was done.

Otherwise, most of the changes here are just minor discrepancies between the commented formula and the actual recipe inputs/outputs. There are still a couple recipes that are unbalanced in these changes though

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/ChromiumChain.java
>          // CrO3 + 2Al -> Cr + Al2O3
```suggestion
        // Cr2O3 + 2Al -> 2Cr + Al2O3
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .fluidInputs(NitricOxide.getFluid(2000))
```suggestion
                .fluidOutputs(NitrogenDioxide.getFluid(2000))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(CopperArsenite.getItemStack(6))
```suggestion
                .outputs(CopperArsenite.getItemStack(12))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .fluidInputs(PotassiumHydroxide.getFluid(8000))
```suggestion
                .fluidInputs(HydrogenCyanide.getFluid(6000))
                .fluidInputs(PotassiumHydroxide.getFluid(4000))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +        // 6HCN + FeCl2 + 4 KOH +  -> K4Fe(CN)6 + 4H2O + 2 HCl
```suggestion
        // 6HCN + FeCl2 + 4 KOH  -> K4Fe(CN)6 + 4H2O + 2 HCl
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .inputs(PotassiumFerrocyanide.getItemStack(17))
```suggestion
                .inputs(PotassiumFerrocyanide.getItemStack(51))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .input(dust, Pyrolusite, 4)
```suggestion
                .input(dust, Pyrolusite, 6)
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .output(dust, ZincSulfate, 5)
```suggestion
                .output(dust, ZincSulfate, 6)
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .output(dust, Saltpeter ,10)
```suggestion
                .output(dust, Saltpeter, 10)
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(DiaminostilbenedisulfonicAcid.getItemStack(19))
Guess this is the first example of it being a "half" mole? Maybe we should divide this whole recipe in half instead of creating half moles for consistency, since every other input/output is easily divisible by two

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +        // 5 C7H7(NO2) + 2C6H5NH2 + HCl -> C42H35N6Cl + NH3 + 4 H2O (divided by 1/2 to fit in small machine)
This recipe is still quite lossy even with the "divide by 1/2" applied.

Left side is missing (in total): 5C, 4H, 6O

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .buildAndRegister();
Dilute sulfuric acid in GTCE is actually 2 parts sulfuric acid to one part water.

I would recommend:
`C10H8 + HNO3 + 2H2SO4 + 6 H -> C10H9N + (H2SO4)2H2O + H2O`, and change to 3B dilute output

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .inputs(SodiumSulfanilate.getItemStack())
```suggestion
                .inputs(SodiumSulfanilate.getItemStack(18))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .outputs(DirectBrown.getItemStack(2))
```suggestion
                .outputs(DirectBrown.getItemStack(36))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(DianilineterephthalicAcid.getItemStack(21))
This one is a little messier but could still be divided fully by two to preserve mole count

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(DiarylideYellow.getItemStack(35))
Same as others, could be fully divided by two

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(AlizarineCyanineGreen.getItemStack(31))
Same as others, could be fully divided by two

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Anthraquinone.getItemStack(26))
```suggestion
                .outputs(Anthraquinone.getItemStack(24))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Anthraquinone.getItemStack(26))
```suggestion
                .outputs(Anthraquinone.getItemStack(24))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .fluidOutputs(DilutedSulfuricAcid.getFluid(3000))
This should be broken up or the recipe should be rebalanced slightly since this will be sulfur-positive

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .fluidOutputs(Water.getFluid(12000))
```suggestion
                .outputs(IndanthroneBlue.getItemStack(48))
                .fluidOutputs(Water.getFluid(2000))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Mauveine.getItemStack(84))
I don't really like this recipe because of how much input is provided, just to then only give half of the actual amount of input back in the Mauveine. I would be in favor of redoing this recipe to be less expensive

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>          LARGE_CHEMICAL_RECIPES.recipeBuilder().duration(200).EUt(1700)
This recipe could fit in singleblock Chemical Reactor, unless this is in LCR only on purpose

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .outputs(Diketopyrrolopyrrole.getItemStack())
```suggestion
                .outputs(Diketopyrrolopyrrole.getItemStack(32))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +        //2 C7H5N + C10H18O4 -> 2 C3H8O + C16H12N2O2
This recipe loses 2 Carbon currently

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .fluidInputs(Aniline.getFluid(1000))
```suggestion
                .fluidInputs(Aniline.getFluid(2000))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Indigo.getItemStack(15))
This one could easily just be 30, without having to divide all by two
```suggestion
                .outputs(Indigo.getItemStack(30))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Tetrabromoindigo.getItemStack(15))
Like above
```suggestion
                .inputs(Indigo.getItemStack(30))
                .fluidInputs(Bromine.getFluid(4000))
                .outputs(Tetrabromoindigo.getItemStack(30))
```

2021-06-21 01:57 UTC, DStrand1 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Erythrosine.getItemStack(20))
Not sure why this was changed, as it was good as 37
```suggestion
                .outputs(Erythrosine.getItemStack(37))
```

2021-06-21 08:02 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .fluidOutputs(DilutedSulfuricAcid.getFluid(3000))
This one is sulfur-neutral, since you have H2SO4 and SO3 in the inputs and output 2H2SO4·H2O

2021-06-21 08:19 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Mauveine.getItemStack(84))
The thing with this one is that if i use potassium dichromate as the oxidising agent, it forces me to those numbers. I don't think i can make the recipe smaller without using small dusts, so i'll need to add a small dust for Cr2O3. The other alternative would be looking for a oxidising agent that plays more nicely with the recipe, but the only one i could find is KMnO4 -> Mn2+

2021-06-21 08:26 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +        //2 C7H5N + C10H18O4 -> 2 C3H8O + C16H12N2O2
The compund made is actually C18H12N2O2

2021-06-21 18:13 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +                .outputs(Mauveine.getItemStack(84))
In the end, i'll divide this by 5, which only loses 1 dust of mauvine every 5 batches, or about 0.6% of output.

2021-06-21 18:24 UTC, pablocnvs commented
The half mole thing was done because i though they might be too op this dyes, but i clearly forgot those would need to compete with vanilla, where all dyes are farmable with relatively easy setups in some cases. This commit will revert that

2021-07-01 17:14 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> -                .outputs(OreDictUnifier.get(dust, Salt, 2))
Sodium hydroxide input is missing here.

2021-07-01 17:14 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>          CHEMICAL_RECIPES.recipeBuilder().duration(520).EUt(1340)
Gtce has a chemical reactor recipe of benzene and oxygen. If that recipe does not have a circuit, we may need to remove it and add a circuit ourselves.

2021-07-01 22:27 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
>                  .fluidInputs(NitroBenzene.getFluid(1000))
That recipe is divided by 2, so it should be actually balanced. The inputs are out of order, keep in mind

2021-07-09 07:56 UTC, merged