HNIW Chain
Gregicality/gregicality pull request #540
Opened 2021-06-21 09:11 UTC by hjae78

This chain isn't finished yet but I'm having issues finding information about the chemical composition of some of the later molecules. I'm hoping that some of the chemist experts can review this and point out my mistakes.

Here is a rough sketch of what I'm working of off: 
![image](https://user-images.githubusercontent.com/54247183/122737166-103d5080-d281-11eb-88b8-07014482e8e2.png)

I'm also attaching a PDF of the paper which I'm using as a reference for the actual synthesis of HNIW.
[1-s2.0-S0040402098830408-main.pdf](https://github.com/Gregicality/gregicality/files/6685462/1-s2.0-S0040402098830408-main.pdf)
 The relevant parts are the two first paragraphs under _Results and Discussion_

2021-06-25 22:48 UTC, pablocnvs commented
I wonder why use the potassium nitrite when we already have the sodium one?

2021-07-02 20:21 UTC, TechLord22 requested changes

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .EUt(30720)
HV.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        //C48N6H48 + 4 C6H7NO4 + 4H -> 4 C7H8 + C28N6H32O4
This isn't representative of the inputs and outputs, and isn't balanced. Also move this out of the chem plant if possible.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .outputs(DibenzylTetraacetylhexaazaisowurtzitane.getItemStack())
Only 1 item here?

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .EUt(1920)
Less eut.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .EUt(30720)
Move this to HV.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .EUt(30720)
HV.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .EUt(1920)
LV.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        BIO_REACTOR_RECIPES.recipeBuilder()
I feel like we already have a recipe like this.

2021-07-02 20:21 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/UHVMaterials.java
>                  .fluidInputs(Glyceryl.getFluid(1000))
Is this still needed?

2021-07-02 20:23 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/chain/UHVMaterials.java
>                  .fluidInputs(Glyceryl.getFluid(1000))
What do you mean?

2021-07-02 20:26 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/UHVMaterials.java
>                  .fluidInputs(Glyceryl.getFluid(1000))
I believe the glyceryl fluid is Glyceryl Trinitride. Do we need both explosives in the recipe?

2021-07-02 21:15 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/chain/UHVMaterials.java
>                  .fluidInputs(Glyceryl.getFluid(1000))
Ah i thought your comment was on the HNIW input, no you're right

2021-07-02 21:20 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        CHEMICAL_PLANT_RECIPES.recipeBuilder()
Sodium Hypochlorite is NaClO

2021-07-02 21:22 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        BIO_REACTOR_RECIPES.recipeBuilder()
We do have glucose to succinic acid, this one is to provide a link between the succinimide produced and the production of succinimidyl acetate

2021-07-02 21:24 UTC, pablocnvs commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final SimpleDustMaterial Tetraacetyldinitrosohexaazaisowurtzitane = new SimpleDustMaterial("tetraacetyldinitrosohexaazaisowurtzitane",(DibenzylTetraacetylhexaazaisowurtzitane.rgb+He
C14N8H18O6, formulas where provided for all of the steps

2021-07-02 21:34 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        CHEMICAL_PLANT_RECIPES.recipeBuilder()
As for the inputs, i think hjae wanted to replicate the procedure he used it in, but given the idealistic conditions we use those fluids would technically be non-consumed ones or at most 1000 for the entire reaction

2021-07-02 21:35 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        CHEMICAL_PLANT_RECIPES.recipeBuilder()
Google seemed to pull up the wrong thing. My bad. If anything else can be used to condense this, that would be nice.

2021-07-02 21:37 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +                .outputs(DibenzylTetraacetylhexaazaisowurtzitane.getItemStack())
I think hjae and i both agreed indirectly that this could be treated as 1mol/dust, since for some of those the corresponding amount of dust would be a bit absurd. We do have some items that surpass the 1 stack in these, and the compounds always show up as 1 mol in the reactions, so....

2021-07-02 21:50 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        //C48N6H48 + 4 C6H7NO4 + 4H -> 4 C7H8 + C28N6H32O4
I think the chemical equation only needs the succinimide to be added, which IIRC is C4H5NO2
C48N6H48 + 4 C6H7NO4 + 16H -> 4 C7H8 + C28N6H32O4 + 4H2O + 4 C4H5NO2 should do the trick

2021-07-02 21:52 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/UHVMaterials.java
>                  .fluidInputs(Glyceryl.getFluid(1000))
Yeah, makes sense to yeet the glyceryl

2021-07-03 21:52 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        CHEMICAL_PLANT_RECIPES.recipeBuilder()
Triethylamine is a catalyst in this reaction, so lower it to 50 mb or not consumed

2021-07-03 21:54 UTC, pablocnvs approved these changes
Well, i don't think i need to comment anything beyond the issues pointed out by Tech, some of which i have already responded giving further clarification. I did revise the chemistry for some of the reactions even before, so there shouldn't be any major issues in that department.

2021-07-06 07:27 UTC, hjae78 commented on src/main/java/gregicadditions/recipes/chain/HNIWChain.java
> +        CHEMICAL_PLANT_RECIPES.recipeBuilder()
There is sodium hydrochloride, ClHNa. I could then output 12000 salt water and 12 sodium hydrochloride instead of salt, water and hydrogen

2021-07-06 07:37 UTC, hjae78 commented
I've resolved the vast majority of your comments. I think you're too aggressive when it comes to nerfing the EU/t but I have lowered the EU/t of every recipe that you commented on.

2021-07-06 12:10 UTC, TechLord22 approved these changes

2021-07-09 07:55 UTC, merged