Fullerene tweaks
Gregicality/gregicality pull request #579
Opened 2021-08-07 17:53 UTC by pablocnvs

Small tweaks to the fullerene chain, modifying the first recipe that had some errors, added some qol recipes regarding HBr and swapped oxygen in the fullerene folding steps (including the one in the superconductor chain) for nitrogen.

2021-08-15 06:26 UTC, DStrand1 approved these changes

2021-08-21 06:49 UTC, TechLord22 requested changes

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final IngotMaterial BlackTitanium = new IngotMaterial(856, "black_titanium", 0x6C003B, MaterialIconSet.SHINY, 7, of(new MaterialStack(Titanium, 26), new MaterialStack(Lanthanum, 6),
What was the reason for this change? It makes progression past approximately UEV impossible, since this is a blast furnace coil material.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/GARecipeMaps.java
> +            0, 4, 0, 3, 0, 5, 0, 4, (new LargeRecipeBuilder(RecipeMaps.CHEMICAL_RECIPES))
This will create some problems with CEu's LCR. Was there really no other way to do the recipe requiring 4 item inputs, or at least break it up? You can also use the chemical plant recipemap if that fits the requirements as well.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        CHEMICAL_RECIPES.recipeBuilder().duration(100).EUt(120)
Should have the chemical equation commented.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +                .input(dust, IridiumChloride, 8)
This reaction loses 1 iridium. It can be rectified by changing to `IrCl3 + 2C8H12 -> (C8H12)2IrCl2 + Cl`.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +                .input(dust, Lithium, 3)
The reaction calls for 4 Lithium, instead of 3.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        //4 Li + PCl3 + 2 C3H8O -> 2 LiCl + 2 LiOH + P(C3H7)2Cl
Please include the water for the solution in this comment.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        //4 P(C3H7)2Cl + (C8H12)2IrCl2 + 2 C6H6OS -> 2 IrP2C18H32SOCl + 2 C8H12 + 2 Cl + 2 HCl (divided by 2)
This reaction loses 1 Ir. I'm not sure how to modify this reaction to fix this though.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/Dyes.java
> +        ALLOY_SMELTER_RECIPES.recipeBuilder().duration(310).EUt(32)
This should use 30 EUt instead of 32.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        CHEMICAL_RECIPES.recipeBuilder()
This recipe needs a reaction comment.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // 3 NaCl + 3 C2H5OH + [C63H15NFe] + CO2 + H2O
This reaction is not chemically balanced.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
>                  .EUt(524288)
This should be changed to around 500k EU. One full amp is quite annoying for this voltage tier.

2021-08-21 06:49 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/REEChain.java
> +        // [REECl3 + 3 H2O] + C16H35O4P(cat.) -> [REE2O3](sep.) + 3 HCl
This reaction is not chemically balanced.

2021-08-21 13:44 UTC, pablocnvs commented on src/main/java/gregicadditions/GAMaterials.java
> +    public static final IngotMaterial BlackTitanium = new IngotMaterial(856, "black_titanium", 0x6C003B, MaterialIconSet.SHINY, 7, of(new MaterialStack(Titanium, 26), new MaterialStack(Lanthanum, 6),
Didn't tweak that, idk how it got there

2021-08-21 14:22 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        //4 P(C3H7)2Cl + (C8H12)2IrCl2 + 2 C6H6OS -> 2 IrP2C18H32SOCl + 2 C8H12 + 2 Cl + 2 HCl (divided by 2)
it actually gains iridium, just that i forgot it was a dimer (will specify that in the name)

2021-08-21 16:14 UTC, TechLord22 requested changes

2021-08-21 16:14 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        //4 P(C3H7)2Cl + (C8H12)2Ir2Cl2 + 2 C6H6OS -> 2 IrP2C18H32SOCl + 2 C8H12 + 2 Cl + 2 HCl (divided by 2)
This reaction seems to loose 2 Hydrogen. I think this can be simply fixed by changing the two chlorine to two hydrochloric acid.

2021-08-21 16:14 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // 3 NaCl + 3 C2H5OH + [C63H15NFe] + CO2
This reaction loses 10 carbon.

2021-08-21 16:15 UTC, pablocnvs commented on src/main/java/gregicadditions/recipes/chain/FullereneChain.java
> +        // 3 NaCl + 3 C2H5OH + [C63H15NFe] + CO2
Didn't update that 😩

2021-08-21 16:23 UTC, TechLord22 commented on src/main/java/gregicadditions/recipes/chain/BrineChain.java
> +        //4 P(C3H7)2Cl + (C8H12)2Ir2Cl2 + 2 C6H6OS -> 2 IrP2C18H32SOCl + 2 C8H12 + 2 Cl + 2 HCl (divided by 2)
Can the formula comment be updated to reflect the recipe changes? Thanks.

2021-08-21 16:28 UTC, TechLord22 approved these changes

2021-08-21 18:08 UTC, merged